version: "3"

services:

  ft_irc:
    image: elguesabal/ft_irc:1.0
    container_name: ft_irc
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4242:4242
    environment:
      - PORT=4242
      - PASSWORD=abc